import assert from 'node:assert/strict';
import {parseQr,total,summary,validStudent,defaultSettings,defaultGrading,categories,rankings,validConfig,factor} from '../app/core/model.ts';
assert.equal(categories.length,8);
assert.equal(total(undefined),0);
const student={id:'s',status:'active',deleted_at:null},day={id:'d',deleted_at:null},evaluation={student_id:'s',day_id:'d',present:true,scores:{quiz:8,bible:9},deleted_at:null};
assert.equal(total(evaluation),27);
const data={students:[student],days:[day],evaluations:[evaluation],finals:[],results:[],settings:defaultSettings,grading:defaultGrading};
const result=summary(student,data);
assert.equal(result.points,60);assert.equal(result.max,800);assert.equal(result.present,1);
assert.equal(summary(student,{...data,days:[{...day,deleted_at:'x'}]}).points,0);
assert.equal(total({...evaluation,deleted_at:'x'}),0);
assert.equal(factor(30,60,200),100);assert.equal(factor(10,0,200),0);
assert.equal(validConfig(defaultGrading.config),true);
assert.equal(validConfig({...defaultGrading.config,parts:[]}),false);
assert.equal(validConfig({...defaultGrading.config,parts:[null]}),false);
assert.equal(validConfig({...defaultGrading.config,daily_max:{...defaultGrading.config.daily_max,unknown:10}}),false);
assert.equal(validConfig({...defaultGrading.config,competition_max:0}),false);
assert.equal(rankings({...data,students:[student,{id:'pending',status:'pending'}]}).length,1);
assert.equal(parseQr('madrasetna:v1:20000000-0000-4000-8000-000000000002'),'20000000-0000-4000-8000-000000000002');
assert.throws(()=>parseQr('https://example.com/student/1'));assert.throws(()=>parseQr('madrasetna:v1:1'));
assert.equal(validStudent('مينا جورج','01012345678','mina_1'),true);
assert.equal(validStudent('مينا جورج','10123','mina_1'),false);
assert.equal(validStudent('مينا جورج','01012345678','ADMIN@abc'),false);
console.log('PASS: dynamic factors, 800-point total, zero denominator, configuration validation, pending exclusion and QR validation.');

