import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile,rm} from 'node:fs/promises';
import ts from 'typescript';
import ExcelJS from 'exceljs';
const out=new URL('./.generated/',import.meta.url);await mkdir(out,{recursive:true});
const source=await readFile(new URL('../app/core/excel.ts',import.meta.url),'utf8');
const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace("'./model'","'../../app/core/model.ts'");
await writeFile(new URL('excel.mjs',out),compiled);
const {downloadWorkbook,parseWorkbook}=await import(new URL('excel.mjs',out));
let blob;const original=URL.createObjectURL;URL.createObjectURL=(b)=>{blob=b;return original(b)};globalThis.document={createElement:()=>({click(){}})};
const {defaultSettings}=await import('../app/core/model.ts');
const s={id:'20000000-0000-4000-8000-000000000002',username:'mina_1',full_name:'مينا جورج',phone:'01012345678',qr_token:'30000000-0000-4000-8000-000000000003',version:1,deleted_at:null};
const d={id:'40000000-0000-4000-8000-000000000004',label:'الأول',date:'2026-09-11',version:1,deleted_at:null};
const e={id:'50000000-0000-4000-8000-000000000005',student_id:s.id,day_id:d.id,present:true,scores:{quiz:8},notes:'ممتاز',version:1,deleted_at:null};
const data={students:[s],days:[d],evaluations:[e],settings:defaultSettings,audit:[]};
await downloadWorkbook(data);let file=new File([await blob.arrayBuffer()],'export.xlsx');let rows=await parseWorkbook(file,data);
assert.equal(rows.length,4);assert.equal(rows.filter(x=>x.error).length,0);assert.equal(rows[0].values.phone,'01012345678');assert.equal(rows.find(x=>x.sheet==='التقييمات').values.quiz,8);
const wb=new ExcelJS.Workbook();await wb.xlsx.load(await file.arrayBuffer());
wb.getWorksheet('التقييمات').getCell('M2').value=11;
rows=await parseWorkbook(new File([await wb.xlsx.writeBuffer()],'invalid.xlsx'),data);
assert.ok(rows.find(x=>x.sheet==='التقييمات').error,'out of range score rejected');
wb.getWorksheet('الأيام').getCell('D2').value='2026-02-30';
rows=await parseWorkbook(new File([await wb.xlsx.writeBuffer()],'invalid-date.xlsx'),data);
assert.ok(rows.find(x=>x.sheet==='الأيام').error,'impossible date rejected');
wb.getWorksheet('الطلاب').getCell('D2').value={formula:'1+1',result:2};
rows=await parseWorkbook(new File([await wb.xlsx.writeBuffer()],'formula.xlsx'),data);assert.ok(rows[0].error,'formulas rejected');
await assert.rejects(()=>parseWorkbook(new File([new Uint8Array(5*1024*1024+1)],'large.xlsx'),data),/5/);
URL.createObjectURL=original;delete globalThis.document;
console.log('PASS: Excel round-trip, Arabic fields, leading-zero phone, score bounds, invalid date, formula and file-size validation.');

