import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();let checks=0;
const admin='10000000-0000-4000-8000-000000000001',a='20000000-0000-4000-8000-000000000002',b='30000000-0000-4000-8000-000000000003',outsider='40000000-0000-4000-8000-000000000004';
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema public,auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;`);
let schema=await readFile(new URL('../supabase/migrations/001_initial.sql',import.meta.url),'utf8');
schema=schema.replace('create extension if not exists pgcrypto;','').replace('alter publication supabase_realtime add table public.profiles,public.days,public.evaluations,public.settings;','');
await db.exec(schema);
await db.query('insert into auth.users values($1),($2),($3),($4)',[admin,a,b,outsider]);
await db.query('insert into public.admins(user_id) values($1)',[admin]);
async function login(id,role='authenticated'){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id||'']);await db.exec('set role '+role)}
async function scalar(sql,args=[]){if(/^select public\.(create_student_profile|save_day|save_profile|save_evaluation|save_settings)\(/.test(sql))sql='select to_jsonb('+sql.slice(7)+')';const result=await db.query(sql,args);return Object.values(result.rows[0]||{})[0]}
async function rejects(sql,args=[],pattern){await assert.rejects(()=>db.query(sql,args),pattern);checks++}
function eq(a,b,label){assert.deepEqual(a,b,label);checks++}
await login(admin);eq(await scalar('select public.is_admin()'),true,'admin recognized');
const sa=await scalar('select public.create_student_profile($1,$2,$3,$4)',[a,'mina_1','مينا جورج','01012345678']);
await scalar('select public.create_student_profile($1,$2,$3,$4)',[b,'mary_2','مريم عادل','01012345679']);
const day=await scalar("select public.save_day(null,'الأول','2026-09-11',0)");
const openDay=await scalar("select public.save_day(null,'يوم مفتوح',null,0)");
await scalar("select public.save_evaluation($1,$2,true,$3,'ملاحظة',0)",[a,day.id,{quiz:8,bible:9}]);
await scalar("select public.save_evaluation($1,$2,false,$3,'خاص بمريم',0)",[b,day.id,{quiz:5}]);
await login(a);
eq(await scalar('select public.is_admin()'),false,'student not admin');
eq(await scalar('select count(*)::int from public.profiles'),1,'student sees own profile only');
eq(await scalar('select id from public.profiles'),a);
eq(await scalar('select count(*)::int from public.evaluations'),1,'student sees own grades only');
eq(await scalar('select count(*)::int from public.audit_log'),0,'audit hidden');
eq(await scalar('select count(*)::int from public.admins'),0,'admin membership hidden');
await rejects("select public.save_profile($1,'متغير','01011111111',1)",[a],/ADMIN_REQUIRED/);
await rejects("select public.scan_attendance($1,$2)",[sa.qr_token,day.id],/ADMIN_REQUIRED/);
await rejects("select public.set_deleted('profiles',$1,true,1)",[b],/ADMIN_REQUIRED/);
await rejects("update public.profiles set full_name='hacked' where id=$1",[a],/permission denied/);
await rejects("insert into public.admins(user_id) values($1)",[a],/permission denied/);
await rejects("insert into public.audit_log(entity,record_id,action) values('x','x','x')",[],/permission denied/);
await rejects("select public.log_password_reset($1)",[a],/ADMIN_REQUIRED/);
await login(outsider);
eq(await scalar('select count(*)::int from public.profiles'),0,'unregistered user has no profiles');
eq(await scalar('select count(*)::int from public.days'),0,'unregistered user has no study data');
await login(null,'anon');
eq(await scalar('select name from public.settings'),'مدرستنا','only branding public');
await rejects('select * from public.profiles',[],/permission denied/);
await rejects('select public.is_admin()',[],/permission denied/);
await login(admin);
await rejects("select public.save_evaluation($1,$2,true,$3,'',1)",[a,day.id,{quiz:11}],/check constraint/);
await rejects("select public.save_evaluation($1,$2,true,$3,'',1)",[a,day.id,{admin:10}],/check constraint/);
await rejects("select public.save_evaluation($1,$2,true,$3,'',1)",[a,day.id,{quiz:'10'}],/check constraint/);
await rejects('select public.scan_attendance($1,$2)',[sa.qr_token,openDay.id],/DAY_NEEDS_DATE/);
const sb=await scalar('select row_to_json(p) from public.profiles p where id=$1',[b]);
const first=await scalar('select public.scan_attendance($1,$2)',[sb.qr_token,day.id]);eq(first.duplicate,false);
const beforeDuplicate=await scalar('select count(*)::int from public.audit_log');
const second=await scalar('select public.scan_attendance($1,$2)',[sb.qr_token,day.id]);eq(second.duplicate,true);
eq(await scalar('select count(*)::int from public.audit_log'),beforeDuplicate,'duplicate scan adds no audit entry');
eq(await scalar('select count(*)::int from public.evaluations where student_id=$1 and day_id=$2',[b,day.id]),1,'one row per day');
const up=await scalar("select public.save_profile($1,'مينا جديد','01012345678',1)",[a]);eq(up.version,2);
await rejects("select public.save_profile($1,'كتابة قديمة','01012345678',1)",[a],/CONFLICT_REFRESH/);
const log=await scalar("select row_to_json(t) from (select * from public.audit_log where entity='profiles' and record_id=$1 and action='update' order by created_at desc limit 1) t",[a]);
eq(log.before_data.full_name,'مينا جورج');eq(log.actor_id,admin);
await scalar('select public.restore_revision($1,2)',[log.id]);
eq(await scalar('select full_name from public.profiles where id=$1',[a]),'مينا جورج','previous profile restored');
await scalar("select public.set_deleted('profiles',$1,true,3)",[a]);
await login(a);eq(await scalar('select count(*)::int from public.profiles'),0,'deleted student loses profile access');eq(await scalar('select count(*)::int from public.evaluations'),0,'deleted student loses grades access');
await login(admin);await rejects('select public.scan_attendance($1,$2)',[sa.qr_token,day.id],/INVALID_QR/);
await scalar("select public.set_deleted('profiles',$1,false,4)",[a]);
await login(a);eq(await scalar('select count(*)::int from public.evaluations'),1,'restored student can read grades');
await login(admin);await scalar('select public.rotate_qr($1)',[a]);
await rejects('select public.scan_attendance($1,$2)',[sa.qr_token,day.id],/INVALID_QR/);
const newToken=await scalar('select qr_token from public.profiles where id=$1',[a]);assert.notEqual(newToken,sa.qr_token);checks++;
await scalar("select public.set_deleted('days',$1,true,1)",[day.id]);
await login(a);eq(await scalar('select count(*)::int from public.evaluations'),0,'deleted day hides scores');
await login(admin);await scalar("select public.set_deleted('days',$1,false,2)",[day.id]);
await rejects("select public.save_settings('x','','','javascript:alert(1)',1)",[],/check constraint/);
await rejects("delete from public.audit_log",[],/permission denied/);
await rejects("delete from public.profiles where id=$1",[a],/permission denied/);
await rejects("select public.set_deleted('admins',$1,true,1)",[a],/INVALID_ENTITY/);
console.log('PASS: '+checks+' database authorization, validation, attendance, concurrency and restore checks.');
await db.close();


