import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {stripTypeScriptTypes} from 'node:module';import {defaultGrading,defaultSettings} from '../app/core/model.ts';import {mergeRows,serialSync} from '../app/core/sync.ts';
const stamp='2026-09-20T10:00:00Z';const db={profiles:[{id:'s',version:1,updated_at:stamp,status:'active',deleted_at:null}],days:[],evaluations:[],settings:[{...defaultSettings,updated_at:stamp,logo:'x'.repeat(200000)}],grading:[{...defaultGrading,updated_at:stamp}],final_scores:[],audit_log:[{id:'a',created_at:stamp,before_data:{logo:'x'.repeat(200000)}}]};let calls=[],admin=true,revision=1,bytes=0;
const mock={rpc:async(name,args)=>{calls.push(name);let data;if(name==='sync_manifest')data={admin,owner:admin,revision,...Object.fromEntries(Object.entries(db).filter(([k])=>k!=='audit_log').map(([k,v])=>[k,{stamp:v.map(x=>x.updated_at).sort().at(-1)||null,count:v.length}])),...(args.p_audit?{audit:{stamp,count:1}}:{})};else if(name==='get_final_scores')data=db.final_scores;else if(name==='get_results')data=[];else throw Error(name);bytes+=JSON.stringify(data).length;return {data,error:null}},from(table){const filters=[];let lo=0,hi=1000;return {select(){return this},order(){return this},gte(k,v){filters.push(x=>x[k]>=v);return this},lte(k,v){filters.push(x=>x[k]<=v);return this},range(a,b){lo=a;hi=b+1;return this},limit(n){hi=n;return this},then(resolve){calls.push(table);const data=db[table].filter(x=>filters.every(f=>f(x))).slice(lo,hi);bytes+=JSON.stringify(data).length;return Promise.resolve({data:structuredClone(data),error:null}).then(resolve)}}}};
globalThis.syncTestClient=mock;let src=stripTypeScriptTypes(await readFile('app/core/api.ts','utf8'));src=src.replace("import { supabase } from './client';",'const supabase=globalThis.syncTestClient;').replace("'./sync'",JSON.stringify(new URL('../app/core/sync.ts',import.meta.url).href)).replace("'./model'",JSON.stringify(new URL('../app/core/model.ts',import.meta.url).href));const {createDataLoader}=await import('data:text/javascript;base64,'+Buffer.from(src).toString('base64'));
const load=createDataLoader();await load();const firstBytes=bytes;assert.ok(firstBytes>200000);assert.ok(!calls.includes('audit_log'));calls=[];bytes=0;await load();assert.deepEqual(calls,['sync_manifest']);assert.ok(bytes<1500);console.log('Unchanged sync payload:',bytes,'bytes; initial dataset:',firstBytes,'bytes');
calls=[];db.evaluations.push({id:'e',student_id:'s',day_id:'d',updated_at:'2026-09-20T11:00:00Z',scores:{quiz:5},present:true});revision++;let data=await load();assert.equal(data.evaluations.length,1);assert.deepEqual(calls,['sync_manifest','evaluations']);calls=[];db.evaluations[0].scores.quiz=8;db.evaluations[0].updated_at='2026-09-20T12:00:00Z';data=await load();assert.equal(data.evaluations.length,1);assert.equal(data.evaluations[0].scores.quiz,8);assert.ok(!calls.includes('settings'));
calls=[];await load({audit:true});assert.ok(calls.includes('audit_log'));calls=[];await load({audit:true});assert.deepEqual(calls,['sync_manifest']);await load();calls=[];await load({audit:true});assert.ok(calls.includes('audit_log'));
db.evaluations=[];data=await load();assert.equal(data.evaluations.length,0);assert.equal(mergeRows([{id:'a',x:1}],[{id:'a',x:2}])[0].x,2);
let release;const seen=[];const sync=serialSync(async value=>{seen.push(value);if(seen.length===1)await new Promise(r=>release=r)},(a,b)=>a+b);const first=sync(1);sync(2);sync(3);release();await first;assert.deepEqual(seen,[1,5]);console.log('Incremental updates, no idle refetch, lazy audit, delete reconciliation and queued sync passed');
