import { useState } from 'react';
import { ScoreConfig, Grading, FinalScore, dailyCategories, categories, validConfig, resultMax, round, factor } from '../core/model';
import { Switch } from '@/components/ui/switch';
import { toast } from 'sonner';
export function GradingForm({ grading, busy, onSave }: {
    grading: Grading;
    busy: boolean;
    onSave: (config: ScoreConfig, published: boolean, version: number, competitionPublished: boolean, projectPublished: boolean) => Promise<void>;
}) {
    const [config, setConfig] = useState(() => structuredClone(grading.config)), [published, setPublished] = useState(grading.results_published), [version] = useState(grading.version);
    const [competitionPublished, setCompetitionPublished] = useState(!!grading.competition_published), [projectPublished, setProjectPublished] = useState(!!grading.project_published);
    function field(key: 'daily_target' | 'parts_target' | 'competition_max' | 'competition_target' | 'project_max' | 'project_target', label: string) { return <label>{label}<input required type="number" min=".01" max="1000000" step="any" value={config[key]} onChange={e => setConfig({ ...config, [key]: Number(e.target.value) })}/></label>; }
    return <form onSubmit={e => { e.preventDefault(); if (!validConfig(config)) {
        toast.error('راجع النهايات: كل نهاية لازم تكون أكبر من صفر.');
        return;
    } void onSave(config, published, version, competitionPublished, projectPublished); }}><div className="result-rule"><b>الإجمالي النهائي: {resultMax(config)} درجة</b><p>الدرجة المحصّلة ÷ النهاية الأصلية × النهاية بعد التحويل.</p></div><section className="panel"><h2>1. التقييم اليومي</h2><p className="muted section-gap">حدد النهاية الأصلية لكل بند في اليوم الواحد. مجموع كل الأيام يتحول إلى {config.daily_target}.</p><div className="grade-inputs">{dailyCategories.map(([key, label]) => <label key={key}>{label}<input required type="number" min=".01" max="1000000" step="any" value={config.daily_max[key]} onChange={e => setConfig({ ...config, daily_max: { ...config.daily_max, [key]: Number(e.target.value) } })}/></label>)}</div><div className="section-gap">{field('daily_target', 'مجموع اليومي بعد التحويل')}</div></section><section className="panel"><h2>2. أجزاء الحفظ</h2><p className="muted">درجات مستقلة تُسجل مرة واحدة لكل جزء، بالإضافة إلى بند الحفظ اليومي.</p><div className="grade-inputs section-gap"><label>عدد الأجزاء<input type="number" min={1} max={100} value={config.parts.length} onChange={e => { const n = Number(e.target.value); if (!Number.isInteger(n) || n < 1 || n > 100)
        return; setConfig({ ...config, parts: Array.from({ length: n }, (_, i) => config.parts[i] || { id: 'part_' + crypto.randomUUID(), label: 'الجزء ' + (i + 1), max: 100 }) }); }}/></label>{field('parts_target', 'مجموع أجزاء الحفظ بعد التحويل')}</div>{config.parts.map((p, i) => <div className="part-row" key={p.id}><label>اسم الجزء {i + 1}<input required maxLength={100} value={p.label} onChange={e => setConfig({ ...config, parts: config.parts.map(x => x.id === p.id ? { ...x, label: e.target.value } : x) })}/></label><label>النهاية الأصلية<input required type="number" min=".01" max="1000000" step="any" value={p.max} onChange={e => setConfig({ ...config, parts: config.parts.map(x => x.id === p.id ? { ...x, max: Number(e.target.value) } : x) })}/></label></div>)}</section><section className="panel"><h2>3. المسابقة والمشروع</h2><p className="muted section-gap">درجة واحدة لكل طالب، مستقلة عن أيام الدراسة.</p><div className="grade-inputs">{field('competition_max', 'النهاية الأصلية للمسابقة')}{field('competition_target', 'المسابقة بعد التحويل')}{field('project_max', 'النهاية الأصلية للمشروع')}{field('project_target', 'المشروع بعد التحويل')}</div></section><div className="attendance-switch"><label htmlFor="publish-competition">عرض درجة المسابقة للطلاب</label><Switch id="publish-competition" checked={competitionPublished} onCheckedChange={setCompetitionPublished}/></div><div className="attendance-switch"><label htmlFor="publish-project">عرض درجة المشروع للطلاب</label><Switch id="publish-project" checked={projectPublished} onCheckedChange={setProjectPublished}/></div><div className="attendance-switch"><label htmlFor="publish-results">إعلان النتيجة والترتيب للطلاب<small>{published ? 'الطالب يرى مجموعه النهائي وترتيبه فقط.' : 'المجموع النهائي والترتيب مخفيان عن الطلاب.'}</small></label><Switch dir="ltr" id="publish-results" checked={published} onCheckedChange={setPublished}/></div><p className="muted">التعادل في المجموع يعطي نفس المركز: 1، 1، 3. البنود غير المسجلة تُحسب صفرًا، وكل أيام الدراسة النشطة محسوبة.</p><button className="primary" disabled={busy}>حفظ نظام الدرجات والإعلان</button></form>;
}
export function FinalScoresForm({ record, config, busy, onSave }: {
    record?: FinalScore;
    config: ScoreConfig;
    busy: boolean;
    onSave: (parts: Record<string, number>, competition: number, project: number, notes: string, version: number) => Promise<FinalScore>;
}) {
    const [parts, setParts] = useState(record && !record.deleted_at ? record.part_scores : {}), [competition, setCompetition] = useState(record && !record.deleted_at ? record.competition : 0), [project, setProject] = useState(record && !record.deleted_at ? record.project : 0), [notes, setNotes] = useState(record?.notes || ''), [version, setVersion] = useState(record?.version || 0);
    return <form onSubmit={async (e) => { e.preventDefault(); try {
        const saved = await onSave(Object.fromEntries(config.parts.map(p => [p.id, parts[p.id] || 0])), competition, project, notes, version);
        setVersion(saved.version);
    }
    catch { } }}><section><h3>أجزاء الحفظ</h3><div className="grade-inputs section-gap">{config.parts.map(p => <label key={p.id}>{p.label}<div className="score-input"><input type="number" min="0" max={p.max} step="any" value={parts[p.id] ?? ''} placeholder="0" onChange={e => setParts({ ...parts, [p.id]: Number(e.target.value) })}/><span>/ {p.max}</span></div></label>)}</div></section><div className="grade-inputs"><label>المسابقة<div className="score-input"><input type="number" min="0" max={config.competition_max} step="any" value={competition} onChange={e => setCompetition(Number(e.target.value))}/><span>/ {config.competition_max}</span></div><small>بعد التحويل: {round(factor(competition, config.competition_max, config.competition_target))} / {config.competition_target}</small></label><label>المشروع<div className="score-input"><input type="number" min="0" max={config.project_max} step="any" value={project} onChange={e => setProject(Number(e.target.value))}/><span>/ {config.project_max}</span></div><small>بعد التحويل: {round(factor(project, config.project_max, config.project_target))} / {config.project_target}</small></label></div><label>ملاحظات<textarea maxLength={2000} rows={2} value={notes} onChange={e => setNotes(e.target.value)}/></label><button className="primary" disabled={busy}>حفظ الدرجات المستقلة</button></form>;
}
