import { useEffect, useState } from 'react';
import { supabase } from '../core/client';
import { account, rpc } from '../core/api';
import { safeError } from '../core/model';
import { Modal } from './ui';
export function ForgotAdminPassword({onClose}:{onClose:()=>void}) {
 const [email,setEmail]=useState(''),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState('');
 return <Modal title="استعادة كلمة مرور الأدمن" description="الاستعادة بالبريد للأدمن والمشرفين فقط. الطالب يطلب كلمة مرور جديدة من الأدمن." onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await account({action:'recover_admin',email:email.trim()});setSent(true)}catch(e){setError(safeError(e))}finally{setBusy(false)}}}><label>بريد حساب الأدمن<input type="email" required maxLength={254} dir="ltr" autoComplete="email" value={email} onChange={e=>{setEmail(e.target.value);setSent(false)}}/></label>{sent&&<p className="notice" role="status">لو البريد مرتبط بحساب أدمن، هيوصلك رابط الاستعادة. راجع الوارد والرسائل غير المرغوب فيها. لو طلبت رابطًا مؤخرًا، استخدم آخر رسالة.</p>}{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy||sent}>{busy?'جاري إرسال الطلب…':'إرسال رابط الاستعادة'}</button></form></Modal>
}
export function ResetAdminPassword({onDone}:{onDone:()=>void}) {
 const [allowed,setAllowed]=useState(false),[checking,setChecking]=useState(true),[password,setPassword]=useState(''),[repeat,setRepeat]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let alive=true;(async()=>{try{const {data,error}=await supabase!.auth.getUser();if(error||!data.user)throw Error('UNAUTHORIZED');if(!await rpc('is_admin',{}))throw Error('ADMIN_REQUIRED');if(alive)setAllowed(true)}catch{if(alive)setError('رابط الاستعادة غير صالح أو منتهي، أو الحساب ليس أدمن. اطلب رابطًا جديدًا.')}finally{if(alive)setChecking(false)}})();return()=>{alive=false}},[]);
 async function leave(){await supabase?.auth.signOut({scope:'local'});history.replaceState(null,'',location.pathname);onDone()}
 return <main className="login-page" dir="rtl"><section className="login-side" style={{gridColumn:'1 / -1',minHeight:'100vh'}}><div className="login-box"><h1>كلمة مرور جديدة للأدمن</h1><p>اكتب كلمة المرور الجديدة واحفظها في مكان آمن.</p>{checking?<p>جاري التحقق من الرابط…</p>:allowed&&<form onSubmit={async e=>{e.preventDefault();setError('');if(password.length<6||password!==repeat){setError('كلمة المرور 6 أحرف على الأقل، والتأكيد لازم يكون مطابق.');return}setBusy(true);try{if(!await rpc('is_admin',{}))throw Error('ADMIN_REQUIRED');const {error}=await supabase!.auth.updateUser({password});if(error)throw error;setPassword('');setRepeat('');await supabase!.auth.signOut();history.replaceState(null,'',location.pathname+'#login');onDone()}catch(e){setError(safeError(e))}finally{setBusy(false)}}}><label>كلمة المرور الجديدة<input type="password" autoComplete="new-password" required minLength={6} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>تأكيد كلمة المرور<input type="password" autoComplete="new-password" required minLength={6} maxLength={128} value={repeat} onChange={e=>setRepeat(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'جاري الحفظ…':'حفظ كلمة المرور وتسجيل الدخول'}</button></form>}{error&&<p className="error" role="alert">{error}</p>}<button className="text-button" disabled={busy} onClick={()=>void leave()}>الرجوع لتسجيل الدخول</button></div></section></main>
}

